/**
 * D19 — compile the corpus into one module.
 * The repo keeps a directory per block (good for review and contribution);
 * the extension ships a single bundled index so activation never touches disk.
 */
import { readFileSync, writeFileSync, readdirSync, existsSync, mkdirSync, statSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const corpus = join(root, 'corpus');
const outDir = join(root, 'src', 'generated');

const readJSON = (p) => JSON.parse(readFileSync(p, 'utf8'));
const dirs = (p) => (existsSync(p) ? readdirSync(p).filter((d) => statSync(join(p, d)).isDirectory()) : []);

const ALLOWED_LICENSES = new Set(['MIT']);
const ALLOWED_ORIGINS = new Set(['authored', 'bootstrap-examples', 'start-bootstrap']);

const blocks = {};
const errors = [];

for (const category of dirs(join(corpus, 'blocks'))) {
  for (const slug of dirs(join(corpus, 'blocks', category))) {
    const dir = join(corpus, 'blocks', category, slug);
    const meta = readJSON(join(dir, 'meta.json'));

    // CI gate: licence + authorship allowlist (D16/D17)
    const prov = meta.provenance || {};
    if (!ALLOWED_LICENSES.has(prov.license)) errors.push(`${slug}: licence "${prov.license}" not on allowlist`);
    if (!ALLOWED_ORIGINS.has(prov.origin)) errors.push(`${slug}: origin "${prov.origin}" not on allowlist`);
    if (prov.author !== 'human') errors.push(`${slug}: provenance.author must be "human"`);
    if (!meta.a11y?.manual?.date) errors.push(`${slug}: missing dated manual a11y review`);

    const variants = {};
    for (const v of ['bootstrap', 'vanilla']) {
      const html = join(dir, `${v}.html`);
      const css = join(dir, `${v}.css`);
      if (existsSync(html)) {
        variants[v] = {
          html: readFileSync(html, 'utf8'),
          css: existsSync(css) ? readFileSync(css, 'utf8') : ''
        };
      }
    }
    const body = Object.values(variants).map((v) => v.html + v.css).join('');
    blocks[meta.id] = {
      ...meta,
      variants,
      hash: createHash('sha256').update(body).digest('hex').slice(0, 16)
    };
  }
}

if (errors.length) {
  console.error('Corpus gate failed:\n  ' + errors.join('\n  '));
  process.exit(1);
}

const tokens = {};
for (const f of readdirSync(join(corpus, 'tokens'))) {
  if (f.endsWith('.json')) { const t = readJSON(join(corpus, 'tokens', f)); tokens[t.id] = t; }
}
const recipes = {};
for (const f of readdirSync(join(corpus, 'recipes'))) {
  if (f.endsWith('.json')) { const r = readJSON(join(corpus, 'recipes', f)); recipes[r.id] = r; }
}
const copy = {};
for (const f of readdirSync(join(corpus, 'copy'))) {
  if (f.endsWith('.json')) { const c = readJSON(join(corpus, 'copy', f)); copy[c.industry] = c; }
}

const index = {
  version: readJSON(join(root, 'package.json')).version,
  blocks,
  tokens,
  recipes,
  copy,
  baseCss: readFileSync(join(corpus, 'base.css'), 'utf8'),
  lexicon: {
    siteTypes: readJSON(join(corpus, 'lexicon', 'site-types.json')),
    stacks: readJSON(join(corpus, 'lexicon', 'stacks.json')),
    sections: readJSON(join(corpus, 'lexicon', 'sections.json')),
    pages: readJSON(join(corpus, 'lexicon', 'pages.json')),
    stopwords: readJSON(join(corpus, 'lexicon', 'stopwords.json'))
  }
};
index.corpusHash = createHash('sha256')
  .update(JSON.stringify({ b: index.blocks, t: index.tokens, r: index.recipes, base: index.baseCss }))
  .digest('hex');

mkdirSync(outDir, { recursive: true });
const out = `// GENERATED by scripts/build-corpus.mjs — do not edit.\n` +
  `import type { CorpusIndex } from '../types.js';\n` +
  `export const CORPUS: CorpusIndex = ${JSON.stringify(index, null, 0)} as unknown as CorpusIndex;\n`;
writeFileSync(join(outDir, 'corpus.ts'), out, { encoding: 'utf8' });

const kb = (Buffer.byteLength(out) / 1024).toFixed(1);
console.log(`corpus: ${Object.keys(blocks).length} blocks, ${Object.keys(recipes).length} recipes, ` +
            `${Object.keys(tokens).length} presets  ->  src/generated/corpus.ts (${kb} KB)`);
console.log(`corpusHash: ${index.corpusHash.slice(0, 16)}...`);
